#+TITLE: notmuch 配置文件
#+AUTHOR: 孙建康（rising.lambda）
#+EMAIL:  rising.lambda@gmail.com
#+DATE: 2024-03-03
#+UPDATED: 2024-03-03
#+LAYOUT: post
#+EXCERPT:  
#+DESCRIPTION: 
#+TAGS: 
#+CATEGORIES: 
#+PROPERTY:    header-args        :comments org
#+PROPERTY:    header-args        :mkdirp yes
#+OPTIONS:     num:nil toc:nil todo:nil tasks:nil tags:nil \n:nil ^:nil *:t <:t -:t f:t |:t ::t
#+OPTIONS:     skip:nil author:nil email:nil creator:nil timestamp:nil
#+INFOJS_OPT:  view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+BIND:        org-preview-latex-image-directory ""
#+OPTIONS:     tex:imagemagick

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [12pt]
#+LaTeX_CLASS_OPTIONS: [koma,a5paper,landscape,twocolumn,utopia,10pt,listings-sv,microtype,paralist]
# No need for a table of contents, unless your paper is quite long.
# Use fancy looking fonts. If you don't have MinionPro installed,
# a good alternative is the Palatino-style pxfonts.
# See: [[http://www.tug.dk/FontCatalogue/pxfonts/][http://www.tug.dk/FontCatalogue/pxfonts/]]
#+LATEX_HEADER:\usepackage{xeCJK}
#+LATEX_HEADER: \usepackage[scaled=.875]{inconsolata}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[scaled]{beraserif}
#+LATEX_HEADER: \usepackage[scaled]{berasans}
#+LATEX_HEADER: \usepackage[scaled]{beramono}
# Set the spacing to double, as required in most papers.
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
# Fix the margins
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
# This line makes lists work better:
# It eliminates whitespace before/within a list and pushes it tt the left margin
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[enumerate,itemize]{noitemsep,nolistsep,leftmargin=*}
# I always include this for my bibliographies
#+LATEX_HEADER: \usepackage[notes,isbn=false,backend=biber]{biblatex-chicago}
#+NAME: attr
#+BEGIN_SRC sh :var data="" :var width="\textwidth" :results output :exports none
  echo "#+ATTR_LATEX: :width $width"
  echo "#+ATTR_ORG: :width $width"
  echo "$data"
#+END_SRC

#+NAME: maildir
#+BEGIN_SRC shell :var maildir=(m/resolve "${m/mail.d}")
  mkdir -p ${maildir}/{sietium,lambda}
  echo ${maildir}
#+END_SRC

*** notmuch 配置文件
    notmuch 的配置文件搜索路径顺序为

    - File specified by notmuch --config global option; see notmuch.

    - File specified by NOTMUCH_CONFIG environment variable.

    - $XDG_CONFIG_HOME/notmuch/<profile>/config where <profile> is defined by NOTMUCH_PROFILE environment variable if set, $XDG_CONFIG_HOME/notmuch/default/config otherwise.

    - $HOME/.notmuch-config.<profile> where <profile> is defined by NOTMUCH_PROFILE environment variable if set, $HOME/.notmuch-config otherwise.

    这里想使用 NOTMUCH_CONFIG 环境变量来制定配置，因为 afew 工具需要依赖环境变量来找到这个配置文件。所以需要配置 zsh 环境变量，以便于读取

    #+BEGIN_SRC shell :tangle (m/resolve "${m/xdg.conf.d}/zsh/rcs/006-notmuch.zsh") :eval never :exports code :comments link :mkdirp yes
      export NOTMUCH_CONFIG=${XDG_CONFIG_HOME}/notmuch/default/config
    #+END_SRC

    #+BEGIN_SRC conf :eval never :exports code :tangle (m/resolve "${m/xdg.conf.d}/notmuch/default/config") :noweb yes :comments link
      # 相对于 HOMEDIR ~ 的目录
      [database]
      mail_root=<<maildir()>>

      [user]
      name=neo
      primary_email=rising.lambda@gmail.com
      other_email=neo@sietium.com;sjkyspa@gmail.com

      [new]
      tags=new;
      ignore=.mbsyncstate;.mbsyncstate.journal;.mbsyncstate.lock;.mbsyncstate.new;.uidvalidity;.isyncuidmap.db

      [search]
      exclude_tags=deleted;spam;

      [maildir]
      synchronize_flags=true
    #+END_SRC

*** pre hook
    #+BEGIN_SRC shell :eval never :exports code :tangle (m/resolve "${m/xdg.conf.d}/notmuch/default/hooks/pre-new") :tangle-mode (identity #o755) :shebang #!/bin/bash :noweb yes :comments link
      proxychains4 -q mbsync -c ${XDG_CONFIG_HOME}/mbsync/config -a
      notmuch new --no-hooks
    #+END_SRC

*** post hook
    #+BEGIN_SRC shell :eval never :exports code :tangle (m/resolve "${m/xdg.conf.d}/notmuch/default/hooks/post-new") :tangle-mode (identity #o755) :shebang #!/bin/bash :noweb yes :comments link
      afew --tag --new
    #+END_SRC

*** post insert hook
    #+BEGIN_SRC shell :eval never :exports code :tangle (m/resolve "${m/xdg.conf.d}/notmuch/default/hooks/post-insert") :tangle-mode (identity #o755) :shebang #!/bin/bash :noweb yes :comments link
      # notmuch tag +sent -new tag:new 'folder:/.*Sent.*/'
    #+END_SRC
